// Generated by gencpp from file laser_scanner_infoscreen/servo_control.msg
// DO NOT EDIT!


#ifndef LASER_SCANNER_INFOSCREEN_MESSAGE_SERVO_CONTROL_H
#define LASER_SCANNER_INFOSCREEN_MESSAGE_SERVO_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laser_scanner_infoscreen
{
template <class ContainerAllocator>
struct servo_control_
{
  typedef servo_control_<ContainerAllocator> Type;

  servo_control_()
    : servo_angle(0)
    , servo_speed(0)  {
    }
  servo_control_(const ContainerAllocator& _alloc)
    : servo_angle(0)
    , servo_speed(0)  {
  (void)_alloc;
    }



   typedef int16_t _servo_angle_type;
  _servo_angle_type servo_angle;

   typedef int16_t _servo_speed_type;
  _servo_speed_type servo_speed;




  typedef boost::shared_ptr< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> const> ConstPtr;

}; // struct servo_control_

typedef ::laser_scanner_infoscreen::servo_control_<std::allocator<void> > servo_control;

typedef boost::shared_ptr< ::laser_scanner_infoscreen::servo_control > servo_controlPtr;
typedef boost::shared_ptr< ::laser_scanner_infoscreen::servo_control const> servo_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser_scanner_infoscreen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/lunar/share/sensor_msgs/cmake/../msg'], 'laser_scanner_infoscreen': ['/home/proto/catkin_test/src/laser_scanner_infoscreen/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c262244dcf1e02f10031616c618a6285";
  }

  static const char* value(const ::laser_scanner_infoscreen::servo_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc262244dcf1e02f1ULL;
  static const uint64_t static_value2 = 0x0031616c618a6285ULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_scanner_infoscreen/servo_control";
  }

  static const char* value(const ::laser_scanner_infoscreen::servo_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 servo_angle\n\
int16 servo_speed\n\
";
  }

  static const char* value(const ::laser_scanner_infoscreen::servo_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_angle);
      stream.next(m.servo_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servo_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_scanner_infoscreen::servo_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_scanner_infoscreen::servo_control_<ContainerAllocator>& v)
  {
    s << indent << "servo_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.servo_angle);
    s << indent << "servo_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.servo_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_SCANNER_INFOSCREEN_MESSAGE_SERVO_CONTROL_H
