// Generated by gencpp from file laser_scanner_infoscreen/trackObjectsRequest.msg
// DO NOT EDIT!


#ifndef LASER_SCANNER_INFOSCREEN_MESSAGE_TRACKOBJECTSREQUEST_H
#define LASER_SCANNER_INFOSCREEN_MESSAGE_TRACKOBJECTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laser_scanner_infoscreen
{
template <class ContainerAllocator>
struct trackObjectsRequest_
{
  typedef trackObjectsRequest_<ContainerAllocator> Type;

  trackObjectsRequest_()
    : a(0.0)  {
    }
  trackObjectsRequest_(const ContainerAllocator& _alloc)
    : a(0.0)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;




  typedef boost::shared_ptr< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct trackObjectsRequest_

typedef ::laser_scanner_infoscreen::trackObjectsRequest_<std::allocator<void> > trackObjectsRequest;

typedef boost::shared_ptr< ::laser_scanner_infoscreen::trackObjectsRequest > trackObjectsRequestPtr;
typedef boost::shared_ptr< ::laser_scanner_infoscreen::trackObjectsRequest const> trackObjectsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser_scanner_infoscreen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/lunar/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a9a8ccf1ae2be3477477819c0d93b4e";
  }

  static const char* value(const ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a9a8ccf1ae2be34ULL;
  static const uint64_t static_value2 = 0x77477819c0d93b4eULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_scanner_infoscreen/trackObjectsRequest";
  }

  static const char* value(const ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct trackObjectsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_scanner_infoscreen::trackObjectsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_SCANNER_INFOSCREEN_MESSAGE_TRACKOBJECTSREQUEST_H
