(cl:defpackage laser_scanner_infoscreen-msg
  (:use )
  (:export
   "<BIOMETRICS>"
   "BIOMETRICS"
   "<BIOMETRICS_RESULTS>"
   "BIOMETRICS_RESULTS"
   "<GESTURE_CALL>"
   "GESTURE_CALL"
   "<SERVO_CONTROL>"
   "SERVO_CONTROL"
   "<SERVO_FEEDBACK>"
   "SERVO_FEEDBACK"
   "<STEPPER_CONTROL>"
   "STEPPER_CONTROL"
   "<STEPPER_FEEDBACK>"
   "STEPPER_FEEDBACK"
  ))

