// Generated by gencpp from file laser_scanner_infoscreen/trackObjects.msg
// DO NOT EDIT!


#ifndef LASER_SCANNER_INFOSCREEN_MESSAGE_TRACKOBJECTS_H
#define LASER_SCANNER_INFOSCREEN_MESSAGE_TRACKOBJECTS_H

#include <ros/service_traits.h>


#include <laser_scanner_infoscreen/trackObjectsRequest.h>
#include <laser_scanner_infoscreen/trackObjectsResponse.h>


namespace laser_scanner_infoscreen
{

struct trackObjects
{

typedef trackObjectsRequest Request;
typedef trackObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct trackObjects
} // namespace laser_scanner_infoscreen


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::laser_scanner_infoscreen::trackObjects > {
  static const char* value()
  {
    return "78b943e796437bdf7a8b6d34c2700469";
  }

  static const char* value(const ::laser_scanner_infoscreen::trackObjects&) { return value(); }
};

template<>
struct DataType< ::laser_scanner_infoscreen::trackObjects > {
  static const char* value()
  {
    return "laser_scanner_infoscreen/trackObjects";
  }

  static const char* value(const ::laser_scanner_infoscreen::trackObjects&) { return value(); }
};


// service_traits::MD5Sum< ::laser_scanner_infoscreen::trackObjectsRequest> should match 
// service_traits::MD5Sum< ::laser_scanner_infoscreen::trackObjects > 
template<>
struct MD5Sum< ::laser_scanner_infoscreen::trackObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::laser_scanner_infoscreen::trackObjects >::value();
  }
  static const char* value(const ::laser_scanner_infoscreen::trackObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_scanner_infoscreen::trackObjectsRequest> should match 
// service_traits::DataType< ::laser_scanner_infoscreen::trackObjects > 
template<>
struct DataType< ::laser_scanner_infoscreen::trackObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::laser_scanner_infoscreen::trackObjects >::value();
  }
  static const char* value(const ::laser_scanner_infoscreen::trackObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::laser_scanner_infoscreen::trackObjectsResponse> should match 
// service_traits::MD5Sum< ::laser_scanner_infoscreen::trackObjects > 
template<>
struct MD5Sum< ::laser_scanner_infoscreen::trackObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::laser_scanner_infoscreen::trackObjects >::value();
  }
  static const char* value(const ::laser_scanner_infoscreen::trackObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::laser_scanner_infoscreen::trackObjectsResponse> should match 
// service_traits::DataType< ::laser_scanner_infoscreen::trackObjects > 
template<>
struct DataType< ::laser_scanner_infoscreen::trackObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::laser_scanner_infoscreen::trackObjects >::value();
  }
  static const char* value(const ::laser_scanner_infoscreen::trackObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LASER_SCANNER_INFOSCREEN_MESSAGE_TRACKOBJECTS_H
