// Generated by gencpp from file laser_scanner_infoscreen/trackObjectsResponse.msg
// DO NOT EDIT!


#ifndef LASER_SCANNER_INFOSCREEN_MESSAGE_TRACKOBJECTSRESPONSE_H
#define LASER_SCANNER_INFOSCREEN_MESSAGE_TRACKOBJECTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laser_scanner_infoscreen
{
template <class ContainerAllocator>
struct trackObjectsResponse_
{
  typedef trackObjectsResponse_<ContainerAllocator> Type;

  trackObjectsResponse_()
    : mobiles_x()
    , mobiles_y()  {
    }
  trackObjectsResponse_(const ContainerAllocator& _alloc)
    : mobiles_x(_alloc)
    , mobiles_y(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _mobiles_x_type;
  _mobiles_x_type mobiles_x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _mobiles_y_type;
  _mobiles_y_type mobiles_y;




  typedef boost::shared_ptr< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct trackObjectsResponse_

typedef ::laser_scanner_infoscreen::trackObjectsResponse_<std::allocator<void> > trackObjectsResponse;

typedef boost::shared_ptr< ::laser_scanner_infoscreen::trackObjectsResponse > trackObjectsResponsePtr;
typedef boost::shared_ptr< ::laser_scanner_infoscreen::trackObjectsResponse const> trackObjectsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser_scanner_infoscreen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/lunar/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/lunar/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "706cc8f892a2bed9fff523be2ea368ba";
  }

  static const char* value(const ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x706cc8f892a2bed9ULL;
  static const uint64_t static_value2 = 0xfff523be2ea368baULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_scanner_infoscreen/trackObjectsResponse";
  }

  static const char* value(const ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] mobiles_x\n\
float32[] mobiles_y\n\
\n\
\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mobiles_x);
      stream.next(m.mobiles_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct trackObjectsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_scanner_infoscreen::trackObjectsResponse_<ContainerAllocator>& v)
  {
    s << indent << "mobiles_x[]" << std::endl;
    for (size_t i = 0; i < v.mobiles_x.size(); ++i)
    {
      s << indent << "  mobiles_x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.mobiles_x[i]);
    }
    s << indent << "mobiles_y[]" << std::endl;
    for (size_t i = 0; i < v.mobiles_y.size(); ++i)
    {
      s << indent << "  mobiles_y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.mobiles_y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_SCANNER_INFOSCREEN_MESSAGE_TRACKOBJECTSRESPONSE_H
